version: 2
formats: [htmlzip]

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    install:
      # 1. Install dependencies manually
      - pip install -r docs/requirements.txt
      - pip install --no-deps .